### ISSUE TITLE
Dockerize the backend

### ISSUE THREAD

**Issue by gabboman** [gabboman/wafrn#115]
If you take a look to the install guide, besides being a bit outdated is hard to replicate. I need a way of easily serving the backend for people wanting to host their own wafrn.

Would be ok to add a initialize command that compiled the backend. I may need to add some changes so by default, the frontend always go for /api and stuff like that, but please let me know about this

**Comment by CPlusPatch** [comment]
I'll try to write a Dockerfile for it or something

**Comment by CPlusPatch** [comment]
Okay, so the issue is that the way Wafrn is configured is a bit annoying, because the installer script does a ton of work that should optimally be done by the user (editing the environment.ts file, setting up a reverse proxy and database, etc.)

So if you want a Docker build then users will have to also remember to set up a MySQL container (which is very easy) and Apache or their favorite reverse proxy (and certbot if they're using a Stone Age proxy)

Otherwise installation + running + healthcheck + running + updates can be done very easily with a Docker build.

**Comment by gabboman** [comment]
there is a docker-compose, it has a postgres thing i use for dev. if you can also use that container it would be neat @CPlusPatch

**Comment by CPlusPatch** [comment]
Oh totally, you'll be able to add the `wafrn` container to that `docker-compose` file fine.

**Comment by CPlusPatch** [comment]
Also, I'm not sure why you have to do that `forceSync` thing, but that will need to either be turned into a config option or outright removed (which would be better).

There are many ways to synchronize the database schema without losing any data

![image](https://github.com/user-attachments/assets/08181aac-6f34-4e81-9a04-fab0347500aa)

**Comment by gabboman** [comment]
> Also, I'm not sure why you have to do that `forceSync` thing, but that will need to either be turned into a config option or outright removed (which would be better).
> 
> There are many ways to synchronize the database schema without losing any data
> 
> ![image](https://private-user-images.githubusercontent.com/42910258/373165587-08181aac-6f34-4e81-9a04-fab0347500aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDI1MTMsIm5iZiI6MTcyNzk0MjIxMywicGF0aCI6Ii80MjkxMDI1OC8zNzMxNjU1ODctMDgxODFhYWMtNmYzNC00ZTgxLTlhMDQtZmFiMDM0NzUwMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA3NTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NTY4ZDQ0ZDg0MjRhNzJmMzJlODJmMTE4M2ViNjBlNjZhNjhkZGJlZmJkYzE0ZWIwMGQ2ZDU5NjQzMzM0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CF6yuYN8qSwFWGULquW4LjRgWjbqiryGgTlc7I8L7Ts)

yeah probably there is a better way of doing this with sequelize but im not sure haha

**Comment by CPlusPatch** [comment]
Try looking for a feature called “migrations” in whatever ORM you use, that might solve the problem

**Comment by gabboman** [comment]
this basicaly is a "force first db creation" thing but yeah. I could create a script that is "setupDatabase" or something like that

**Comment by CPlusPatch** [comment]
Yeah it creates all the necessary tables and columns right?

**Comment by gabboman** [comment]
and the admin user (equivalent of instance actor lol) and deleted user

**Comment by CPlusPatch** [comment]
So you can fix this by setting forceSync to `false` and removing the instruction to set it to `true` (it will still create tables and columns if they don't exist).

Then, to create the relevant admin and deleted users, you can run a check on startup to see if they exist: if not, create them (this also acts as a brick protection I guess)

![image](https://github.com/user-attachments/assets/db4e5be2-036c-4915-b3ad-28b42e03e3f8)

Relevant Sequelize docs -> https://sequelize.org/docs/v7/models/model-synchronization/

**Comment by gabboman** [comment]
@CPlusPatch I have improved the thing :D I hope this can help a bit

**Comment by CPlusPatch** [comment]
oh shit i forgot :trollface:

**Comment by Hoverth** [comment]
I've been giving this a bit of a shot. Some issues I've run into are:

- All the variables in `environment.ts` cannot be changed on-the-fly. I would suggest most of them be changed to read environment variables instead.
- If `logs` doesn't exist as a directory, it will fail on start-up (due to not being able to write `logs/backendlog.log`). This means that with `tsx index.ts` run in the `packages/backend` directory, it'll be looking for a `packages/backend/logs` directory
- The database URL is hard-coded, would probably be good to expose as an environment variable too.
- If the database `wafrn` doesn't exist, it'll exit with an error.
- The backend wants the location of the frontend, which may mean that both the frontend & backend have to be in the same container, or that functionality needs to be removed to keep them separate.

I'm willing to create a PR with what I have so far, if you want to look over it, though it does not work at the moment.

**Comment by Hoverth** [comment]
Update: I have managed to get the backend container starting without any errors.

**Comment by Hoverth** [comment]
From what I can see, the repo is currently setup up expecting both the backend and the frontend setup on the same server, and the frontend + static files are served by apache, which also acts as a reverse-proxy to the backend.

I'm not sure how you want the backend dockerized in this current iteration, as it seems rather interconnected with the frontend at the moment, I'll need some input from you going forward.

**Comment by gabboman** [comment]
please do! yeah youre right some stuff is a bit scatered.

I am planing on looking into using caddy instead of apache. Reason being: bsky is coming

**Comment by Hoverth** [comment]
I can definitely help with moving stuff to caddy, as all my self-hosted stuff uses it, so I'm pretty familiar with it.

**Comment by CPlusPatch** [comment]
Probably also consider using a slightly richer format for the config than `.env` files, such as TOML.

[`unjs/c12`](https://github.com/unjs/c12) is great for loading config from all sorts of formats without having to worry about it (choose your favourite).

**Comment by Hoverth** [comment]
Loading variables into docker through environment variables enables multiple docker containers to be able to use the same variables without rebuilding, and means that if we use variables that match other containers (like the postgres credentials) then it'll just work, no matter what those variables are set to.
